---
# tasks file for roles/wordpress
- name: Install epel-release
  ansible.builtin.dnf:
    name: 
      - epel-release 
      - tar
    state: present

- name: Import tasks user
  ansible.builtin.import_tasks: user.yml

- name: Import tasks httpd
  ansible.builtin.import_tasks: httpd.yml

- name: Import tasks mariadb
  ansible.builtin.import_tasks: mariadb.yml

- name: Import tasks php
  ansible.builtin.import_tasks: php.yml

- name: Import tasks wordpress
  ansible.builtin.import_tasks: wordpress.yml
