---
- name: Install mariadb
  ansible.builtin.dnf:
    name: mariadb-server
    state: present
  notify: Secure_mariadb

- name: Start and enable mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create a new mysql database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create a new mysql user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    host: "%"
    priv: '"{{ db_user }}".*:ALL'
    password: "{{ mysql_wordpress_pass }}"
    state: present
    check_implicit_admin: true
    login_unix_socket: /var/lib/mysql/mysql.sock
