---
- name: Download wordpress
  ansible.builtin.get_url:
    url: "{{ wordpress_url }}"
    dest: /var/www/html/
    mode: "0644"

- name: Check if wordpress directory exists
  ansible.builtin.stat:
    path: "{{ wordpress_docroot }}"
  register: wordpress_directory

- name: Extract wordpress
  ansible.builtin.unarchive:
    src: /var/www/html/wordpress-6.3.2.tar.gz
    dest: /var/www/html/
    remote_src: true
  when: not wordpress_directory.stat.exists
  notify: Change_permissions

- name: Check current SELinux context for /var/www/html/wordpress
  community.general.sefcontext:
    target: "{{ wordpress_docroot }}"
    setype: httpd_sys_rw_content_t
    seuser: system_u

- name: Apply new SELinux file context to filesystem
  ansible.builtin.command: restorecon -Rv /var/www/html/wordpress
  register: my_output
  changed_when: my_output.rc != 0
